name: mlops_g1

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.10

  # Core data + ML
  - pandas
  - numpy
  - scikit-learn
  - joblib

  # Config + utilities
  - pyyaml
  - python-dotenv

  # API stack
  - fastapi
  - uvicorn

  # Dev / notebooks
  - jupyter
  - ipykernel

  # Testing
  - pytest
  - pytest-cov

  # Pip-only packages
  - pip
  
  - wandb
  - matplotlib
  - seaborn