[pytest]
# Tell pytest to look for tests in the "tests" directory
testpaths = tests 
 # Recognize test files that start with "test_" and end with ".py"
python_files = test_*.py
# Ignore common non-code directories to speed up test discovery
norecursedirs = notebooks env venv .venv .git __pycache__ 
# Add options to pytest: -q for quiet output, --cov for coverage reporting
addopts = -q